name: Reddit RSS to Discord

# Give the workflow write access to the repo (needed for private repos)
permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:       # allows manual run

jobs:
  rss-job:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run your app.py script
      - name: Run Reddit to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python app.py

      # 5️⃣ Commit updated posted.json back to the repo
      - name: Commit posted.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posted.json
          git commit -m "Update posted.json" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
